### ISSUE TITLE
video

### ISSUE THREAD

**Issue by dle666** [dle666/R-CoT#1]
https://github.com/user-attachments/assets/1c3c578b-c689-4638-9dfe-e0b67ec2650d

**Comment by panhongai66** [comment]
It is quite interesting that although this is multimodal rather than single-text modal, one can't help but wonder if the idea is inspired by **Reversal of Thought**. I am very grateful to the author for creating a dataset and conducting many experiments and some open-source work. However, the overall approach seemingly borrows from "Reversal of Thought". If there is a referenced idea, I think this work is also a reaffirmation of **Reversal of Thought**. It is advisable for the author to cite relevant works to clarify the motivation.  https://arxiv.org/abs/2410.12323

**Comment by XiaoZhao-35** [comment]
**issue #2**  😊

**Comment by Yuliang-Liu** [comment]
Feel free to reopen if there is any issue related to the video.
